version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    groups:
      major:
        update-types:
          - major
      patches:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    labels:
      - dependencies
      - github-actions
