import type { LoadTestReport } from '@reaatech/mcp-load-test-core';

export class MarkdownReporter {
  format(report: LoadTestReport): string {
    const lines: string[] = [];

    lines.push('# Load Test Report');
    lines.push('');

    // Summary
    lines.push('## Summary');
    lines.push(`- **Grade:** ${report.grade}`);
    if (report.breakingPoint?.detected) {
      lines.push(
        `- **Breaking Point:** ${report.breakingPoint.concurrencyAtBreak} concurrent sessions`,
      );
    }
    lines.push(`- **Duration:** ${this.formatDuration(report.durationMs)}`);
    lines.push(`- **Total Requests:** ${report.throughput.totalRequests.toLocaleString()}`);
    lines.push(`- **Endpoint:** ${report.endpoint}`);
    lines.push('');

    // Latency
    lines.push('## Latency');
    lines.push('| Tool | p50 | p90 | p95 | p99 | Samples |');
    lines.push('|------|-----|-----|-----|-----|---------|');
    for (const tl of report.toolLatencies) {
      lines.push(
        `| ${tl.toolName} | ${tl.latency.p50.toFixed(0)}ms | ${tl.latency.p90.toFixed(0)}ms | ${tl.latency.p95.toFixed(0)}ms | ${tl.latency.p99.toFixed(0)}ms | ${tl.latency.samples.toLocaleString()} |`,
      );
    }
    lines.push('');

    // Throughput
    lines.push('## Throughput');
    lines.push(`- **Average RPS:** ${report.throughput.averageRps.toFixed(1)}`);
    lines.push(`- **Peak RPS:** ${report.throughput.peakRps.toFixed(1)}`);
    lines.push(`- **Successful:** ${report.throughput.totalSuccessful.toLocaleString()}`);
    lines.push(`- **Failed:** ${report.throughput.totalFailed.toLocaleString()}`);
    lines.push('');

    // Breaking point
    if (report.breakingPoint?.detected) {
      lines.push('## Breaking Point Analysis');
      lines.push(
        `Server began degrading at **${report.breakingPoint.concurrencyAtBreak}** concurrent sessions:`,
      );
      lines.push(
        `- Error rate increased to ${((report.breakingPoint.errorRateAtBreak || 0) * 100).toFixed(1)}%`,
      );
      lines.push(
        `- p99 latency increased to ${report.breakingPoint.latencyP99AtBreak?.toFixed(0)}ms`,
      );
      if (report.breakingPoint.recoveryTimeMs) {
        lines.push(
          `- Recovery time: ${this.formatDuration(report.breakingPoint.recoveryTimeMs)} after load reduction`,
        );
      }
      lines.push('');
    }

    // Errors
    if (report.errorSummary.totalErrors > 0) {
      lines.push('## Errors');
      lines.push(
        `- **Total Errors:** ${report.errorSummary.totalErrors} (${(report.errorSummary.errorRate * 100).toFixed(2)}%)`,
      );
      lines.push('');
      lines.push('| Category | Count |');
      lines.push('|----------|-------|');
      for (const [category, count] of Object.entries(report.errorSummary.byCategory)) {
        lines.push(`| ${category} | ${count} |`);
      }
      lines.push('');
    }

    // Recommendations
    if (report.recommendations.length > 0) {
      lines.push('## Recommendations');
      for (let i = 0; i < report.recommendations.length; i++) {
        lines.push(`${i + 1}. ${report.recommendations[i]}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push(`*Generated by mcp-load-test at ${report.completedAt}*`);

    return lines.join('\n');
  }

  private formatDuration(ms: number): string {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    if (hours > 0) {
      return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
    }
    if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    }
    return `${seconds}s`;
  }
}
